dbz-engine/src/main/java/com/example/DebeziumRunner.java, format_converter.c, replication_agent.c, synchdb.c, synchdb.h
performance increased by completing the batch of changes in one single transaction rather than one transaction per change. This makes processing much faster but also renders 'partial batch completion' useless, so it is removed. Synchdb will only marks the entire batch as complete or failed similar to how a transaction works.
=> significantly reduce the time needed to complete a large initial snapshot

dbz-engine/src/main/java/com/example/DebeziumRunner.java, replication_agent.c, synchdb.c, synchdb.h
debezium has a lot of parameters that we can tune, and so far we have exposed a few of them and we may expose more in the future. To make it easier to pass increasing number of parameters to debezium on the java side, I have consolidated some of the frequently used parameters into a MyParameters inner class inside DebeziumRunner. So Synchdb extension on PostgreSQL side can incrementally construct this MyParameters object and pass it down to Debezium as a single argument rather than multiple.
When we decide to expose more debezium parameters as configurable we simply write some code to incrementally add new parameters to MyParameters object class on both java and synchdb sides.
Also tested a 100k table initial snapshot with mode "no_data", and it requires at least 2G memory allocated to …
=> consolidate debezium configuration parameters into one single java object

dbz-engine/pom.xml, dbz-engine/src/main/java/com/example/DebeziumRunner.java, format_converter.c, synchdb--1.0.sql, synchdb.c, synchdb.h
1. exposed the following debezium parameters to postgreSQL GUCs:
* snapshotThreadNum (synchdb.dbz_snapshot_thread_num)
* snapshotFetchSize (synchdb.dbz_snapshot_fetch_size)
* snapshotMinRowToStreamResults (synchdb.dbz_snapshot_min_row_to_stream_results)
* incrementalSnapshotChunkSize (synchdb.dbz_incremental_snapshot_chunk_size)
* incrementalSnapshotWatermarkingStrategy (synchdb.dbz_incremental_snapshot_watermarking_strategy)
* offsetFlushIntervalMs (synchdb.dbz_offset_flush_interval_ms)
* captureOnlySelectedTableDDL (synchdb.dbz_capture_only_selected_table_ddl)
2. exposed the following tls debezium parameters to rule file:
```
"ssl_rules":
{
"ssl_mode": "disabled",
"ssl_keystore": null,
"ssl_keystore_pass": null,
"ssl_truststore": "fggg",
"ssl_truststore_pass": "ffff"
}
```
3. added an …
=> Exposed several performance and TLS related parameters to GUCs 

dbz-engine/src/main/java/com/example/DebeziumRunner.java
leaving this config there in debezium may cause trouble later because this is a special signaling table for triggering incremental snapshot and actually not being captured. Incremental snapshot is to be supported later but for now, so we will add it back one everything is thoroughly tested
=> remove signal table for incremental snapshot setting for now

format_converter.c
the default data type mapping would try to map char -> char with size 0, which defaults to 1 in PostgreSQL. This is incorrect. We should set the default mapping size to -1. which means to use whatever size debezium change event tells us.
=> fixed an issue where char is mapped to incorrect size in sqlserver connector

dbz-engine/src/main/java/com/example/DebeziumRunner.java, format_converter.c, format_converter.h, replication_agent.c, replication_agent.h, synchdb--1.0.sql, synchdb.c, synchdb.h
added synchdb_stats_view() to collect and show connector statistic info
These statistics record cumulative measurements about different types of change events a connector has processed so far. Currently these statistic values are stored in shared memory and not persisted to disk. Persist statistics data is a feature to be added in near future.
See below for an example output:
```sql
postgres=# select * from synchdb_stats_view;
connector   | ddls |  dmls   |  reads  | creates | updates | deletes | bad_events | total_events | batches_done | avg_batch_size
---------------+------+---------+---------+---------+---------+---------+------------+--------------+--------------+----------------
mysqltpccconn |   22 | 3887111 | 3263746 |  208684 |  400241 |   14440 |      14444 |      3901573 | …
```
=> added synchdb_stats_view() to collect and show connector statistics info

synchdb--1.0.sql, synchdb.c, synchdb.h
* a connector's stats can be reset with synchdb_reset_stats('name'). User has to specify a connector name to reset, it does not reset all stats
* synchdb_states_view and synchdb_stats_view will now only display active entries only
* fixed a crash when automatically launching more than one connector at postgresql startup
* max number of connector workers that synchdb can spawn is now configurable as `synchdb.max_connector_workers`
* adjust the output of synchdb_state_view to match synchdb_stats_view such that `name` is the first column
=> added synchdb_reset_stats, make max connectors configurable, and fix auto startup issues

dbz-engine/src/main/java/com/example/DebeziumRunner.java, dbz-engine/src/main/resources/log4j.properties, replication_agent.c, synchdb.c, synchdb.h
1) added a new GUC synchdb.error_handling_strategy to control the strategy to handle an error: can be skip, exit or retry.
default is `exit`, which means the connector will exit when it encounters an error during apply. Can also be `skip`, which will make the connector skip the error (this causes the "bad event" statistics to increment) without exiting. Or set to `retry` to cause the connector to exit, and then restarted by postgresql to process the last change event again.
2) added a new GUC synchdb.dbz_log_level to control the log level of log4j used by Debezium runner engine
new GUCs to control the log level of debezium runner engine so we have an option to see debezium's working logs if desired
=> added new GUCs to control error handling strategies and log levels

dbz-engine/pom.xml, dbz-engine/src/main/java/com/example/DebeziumRunner.java, format_converter.c, format_converter.h, replication_agent.c, synchdb.c
* oracle connector type can now be selected when creating a connector info
* support interval data type and its variants 
* support oracle's variable scale numbers 
* support CREATE, INSERT, UPDATE and DELETE operations for oracle
* if connector encounters an error, it will print the JSON change event in log to help with debugging. This can be controlled by the new GUC `synchdb.log_change_on_error`
known issue:
if source table has BLOB, CLOB or NCLOB data type and synchdb has configuration synchdb_dml_use_spi = true, then UPDATE and DELETE will not actually be done because Oracle does not supply the old value of BLOB, CLOB, or NCLOB during update or delete so synchdb would not be able to identify the old tuple to update. This would not be an issue if synchdb_dml_use_spi = false, which is …
=> enabled oracle connector in SynchDB

format_converter.c, format_converter.h, replication_agent.c
* support multi-length and scale NUMBER data type from Oracle. When receives a column has data type of NUMBER from Oracle, it will look at the length and scale values as well before doing a data type mapping. When scale is 0, it suggests an integer type of data type and depending on the length, we could map them to different fixed-size integer types such as SMALLINT, BIGINT...etc. If no scale or length are supplied, or when scale is larger than 0, it shall be mapped to numeric data type in postgresql
* fixed an issue with failed update and delete when DML mode is set to SPI and table contains BLOB, CLOB, or NCLOB. This is because Oracle does not log the old values of BLOB, CLOB or NCLOB, so synchdb is not able to determine the tuple to update / delete. By making it only considering the …
=> support multi-length and scale NUMBER data type from Oracle

format_converter.c, format_converter.h, replication_agent.c, testenv/README.md
1. updated testenv readme to include procedure to setup oracle test env.
2. when synchdb.dml_use_spi = true and no primary key exists in the target table, it will refuse to process update and delete
3. when synchdb.dml_use_spi = true, synchdb will only consider primary keys in the WHERE clause instead of all columns before values, as they may not always result in exact match, causing inconsistency. 
4. fixed an issue where synchdb occasionally incorrectly looks up a column's additional schema value from the json change event, causing subsequent processing to fail. This concerns with timestamp related data types 
5. fixed a problem in 'skip on error' mode to panic due to error stack overflow 6) adjusted certain default data type mappings and their handlings to be compatible in postgresql. …
=> adjustment and bugfixes on oracle connector to pass tpcc tests

Makefile, format_converter.c, replication_agent.h, synchdb--1.0--1.1.sql, synchdb--1.0.sql, synchdb.c, synchdb.control, synchdb.h
1. synchdb creates a new table 'synchdb_attribute' that stores all the demote table attributes infor that synchdb is currently capturing. 
2. added a new view 'synchdb_att_view' that will join the contents from pg_attribute and synchdb_attribute to show a side-by-side comparison of data type, table and column name mappings
3. when alter table change event wants to add a primary key, synchdb will only do so when the table has no primary key
4. remove the ability to configure a connector to connect to a different database other than the one where synchdb is installed.
5. at the end of every DDL change event processing, synchdb will attempt to update the synchdb_attribute table
=> initial commit for synchdb v1.1 with new table attribute comparison view

dbz-engine/src/main/java/com/example/DebeziumRunner.java, format_converter.c, format_converter.h, replication_agent.c, replication_agent.h, synchdb--1.0--1.1.sql, synchdb--1.0.sql, synchdb.c, synchdb.h
summary of features added in this pr:
1) normalized all the data type mapping entries to use lower case letters
2) added a new tabled called synchdb_objmap to store differet object mapping entries
3) added a new sql function synchdb_add_objamp to add new object mapping entries, it supports table name, column name, data type and transform expressions
4) added a new sql function synchdb_reload_objmap to force a connector to reload object mapping entries
5) a connector will adjust and correct table name, column name and data type when the configured object mapping differs from current values
6) rulefile is no longer required and used. This has been replaced by synchdb_add_objmap
7) added a new snapshot mode called 'schemasync' in which the connector will obtain schemas and create the tables …
=> Synchdb devel

.github/workflows/synchdb-ci.yml, ci/build-synchdb.sh, ci/setup-remotedbs.sh, ci/test-synchdb.sh, format_converter.c, replication_agent.c, synchdb.c
1) fixed warnings reported by different gcc versions in various build platforms
2) added github workflow to automatically build and test synchdb in all supported postgresql major versions and run sanity tests using supported heterogeneous databases (mysql, oracle and sqlserver). This is only a sanity test that tests only the core functionalities of synchdb. A full regression test cases will need to be designed and implemented in near future
=> Fixed warnings and added github workflow CI sanity tests

format_converter.c, format_converter.h
1) the schema fields of debezium json event is now parsed more efficiently and we now consider the data type field to help select a proper processing routine
2) modularize the core data processing logic in format_converter such that it is possible to define a specific routine to handle a particular input to output type conversion. This was previously not possible if input and output data type are way too 'different'. For example, numeric to date conversion, string to numeric conversion...etc 
3) non-native data types are now processed based on their category indicated by postgresql catalog, rather than treating it as a string always. This allows us to handle most (if not all) data types that are added by other extensions (postgis, ivorysql...etc)
4) data processing logic is now more …
=> modularize the core data processing engine to allow flexible handling of native and non-native data types as well as more complex conversions

format_converter.c, format_converter.h
crash happens when data cache is used to process a oracle change event with less than created column numbers. The natts is not used and cached. This pullrequest fixes this to avoid the crash during apply
=> fixed a potential crash when using cached tupdesc where natts is not saved by mistake

ci/setup-remotedbs.sh, ci/teardown-remotedbs.sh, dbz-engine/src/main/java/com/example/DebeziumRunner.java, synchdb.c, test/hammerdb/test_tpcc.py, testenv/oracle/synchdb-oracle-test.yaml
1) enhanced the performance by reducing JNI calls during during getChangeEvents(). This is achieved by replacing the List<String> it used to return with one serialized direct buffer that the C side can process directly instead of calling JNI to access the List resource and iterate over the list via JNI. Observed a 5% increase in benchmark
2) enhanced the test suite by using docker images hosted in hgneon dockerhub rather than their original source to ensure consistency of test results across different machines. Also add an option to setup oracle 19c though the test currently does not use it because it takes too long to set up. Still keep it in there in case we would like to set up one for manual testing
=> enhance performance by reducing JNI calls

Makefile, ci/build-synchdb.sh, replication_agent.c, synchdb--1.0.sql, synchdb.c, synchdb.h
1) added new function synchdb_add_jmx_conninfo to configure jmx endpoint for monitoring with jconsole or similar sort
2) added new function synchdb_add_jmx_exporter_conninfo to configure jmx exporter for prometheus and graphana monitoring
3) fixed a memory context issue when reading connector info at connector startup 
4) fixed dbz_engine install dir to use pkglibdir rather than libdir. This solves the issue when building with custom prefix that synchdb fails to locate dbz_engine from default location.
=> support for jmx and jmx exporter + bug fixes

format_converter.c, replication_agent.c, synchdb.c
fixed assert errors when postgres is built with --enable-cassert。 This patch fixes[ issue 153](https://github.com/Hornetlabs/synchdb/issues/156)
=> fixed assert errors when postgres is built with --enable-cassert

src/backend/debezium/src/main/java/com/example/DebeziumRunner.java, src/backend/executor/replication_agent.c, src/backend/synchdb/synchdb.c, src/include/synchdb/synchdb.h, synchdb--1.0.sql
1) added infinispan support via synchdb_add_infinispan() and synchdb_del_infinispan()
2) fixed a problem where debezium print duplicate logs when connector is resumed from paused state
3) fixed a problem where offset file fails to load on connector startup
=> infinispan support for oracle debezium connector to support large transaction handling

.github/workflows/synchdb-ci.yml, ci/setup-remotedbs.sh, ci/teardown-remotedbs.sh, src/backend/converter/format_converter.c, src/backend/converter/olr_event_handler.c, src/test/pytests/hammerdb/test_tpcc.py, src/test/pytests/synchdbtests/common.py, src/test/pytests/synchdbtests/conftest.py, src/test/pytests/synchdbtests/t/test_001_initialsnapshot.py, src/test/pytests/synchdbtests/t/test_002_ddl.py, testenv/hammerdb/ora19c_buildschema.tcl, testenv/hammerdb/ora19c_runtpcc.tcl, testenv/olr/synchdb-olr-test.yaml
1) resolved an issue where synchdb will error out if a table or schema name contains space
2) added test_002_ddl test scripts 
3) resolved tpcc run issues
4) resolved github action out of space issues for OLR and oracle tests
5) use oracle19c to run oracle tests instead of oracle 23ai
6) various env fixes to make CI testing pass
=> synchdb test updates
